[package]
name = "integration_tests"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
edition = "2018"
autotests = false

[dependencies]
diesel = { version = "1.0.0", features = ["postgres", "r2d2"] }
swirl = { path = "../swirl" }
lazy_static = "1.0.0"
dotenv = "0.11"
antidote = "1.0.0"
assert_matches = "1.0.0"
failure = { version = "*", features = ["backtrace"] }

[[test]]
name = "integration_tests"
path = "tests/lib.rs"
harness = true

[features]
nightly = ["swirl/nightly"]
